/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import DAOs.DAOaluno;
import DAOs.DAOcurso;
import Entidades.Aluno;
import Entidades.Curso;
import com.sun.jdi.connect.spi.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Usuario
 */
public class GUIaluno extends javax.swing.JFrame {

    /**
     * Creates new form GUIaluno
     */
    public GUIaluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        RATF = new javax.swing.JTextField();
        pesqAlunoBT = new javax.swing.JButton();
        nomeAlunoTF = new javax.swing.JTextField();
        emailAlunoTF = new javax.swing.JTextField();
        telefoneTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboCurso = new javax.swing.JComboBox<>();
        buscarBT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CursoSelect = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addAluno = new javax.swing.JMenuItem();
        saveAluno = new javax.swing.JMenuItem();
        delAluno = new javax.swing.JMenuItem();
        attAluno = new javax.swing.JMenuItem();
        listAluno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cursoAluno = new javax.swing.JMenuItem();
        turmaAluno = new javax.swing.JMenuItem();
        discAluno = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem9.setText("jMenuItem9");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel1.setText("RA:");

        RATF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RATFActionPerformed(evt);
            }
        });

        pesqAlunoBT.setBackground(new java.awt.Color(153, 255, 153));
        pesqAlunoBT.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        pesqAlunoBT.setForeground(new java.awt.Color(0, 0, 51));
        pesqAlunoBT.setText("Pesquisar");
        pesqAlunoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqAlunoBTActionPerformed(evt);
            }
        });

        nomeAlunoTF.setForeground(new java.awt.Color(153, 153, 153));

        emailAlunoTF.setForeground(new java.awt.Color(153, 153, 153));

        telefoneTF.setForeground(new java.awt.Color(153, 153, 153));

        tabelaAluno.setBackground(new java.awt.Color(204, 0, 255));
        tabelaAluno.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        tabelaAluno.setForeground(new java.awt.Color(255, 255, 255));
        tabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Nome", "Email", "Telefone", "Curso"
            }
        ));
        jScrollPane2.setViewportView(tabelaAluno);

        jLabel2.setText("Nome");

        jLabel3.setText("E-mail");

        jLabel4.setText("Telefone");

        jLabel5.setText("Curso");

        comboCurso.setBackground(new java.awt.Color(204, 0, 0));
        comboCurso.setForeground(new java.awt.Color(255, 255, 255));
        comboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCursoActionPerformed(evt);
            }
        });

        buscarBT.setBackground(new java.awt.Color(0, 204, 204));
        buscarBT.setForeground(new java.awt.Color(255, 255, 255));
        buscarBT.setText("Buscar Cursos");
        buscarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBTActionPerformed(evt);
            }
        });

        jLabel6.setText("Curso Selecionado");

        jMenuBar1.setBackground(new java.awt.Color(51, 255, 255));

        jMenu1.setText("Arquivos");

        addAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/botao-adicionar.png"))); // NOI18N
        addAluno.setText("Adicionar");
        addAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(addAluno);

        saveAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/verificado.png"))); // NOI18N
        saveAluno.setText("Salvar");
        saveAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(saveAluno);

        delAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lixeira.png"))); // NOI18N
        delAluno.setText("Deletar");
        delAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(delAluno);

        attAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar.png"))); // NOI18N
        attAluno.setText("Atualizar");
        attAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(attAluno);

        listAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lista-de-papel.png"))); // NOI18N
        listAluno.setText("Listar");
        listAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(listAluno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cruds");

        cursoAluno.setText("Crud Curso");
        cursoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(cursoAluno);

        turmaAluno.setText("Crud Turma");
        turmaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(turmaAluno);

        discAluno.setText("Crud Disciplina");
        discAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(discAluno);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(RATF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesqAlunoBT)
                .addGap(376, 416, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CursoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(nomeAlunoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(emailAlunoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(buscarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesqAlunoBT))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeAlunoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAlunoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(buscarBT))
                .addGap(9, 9, 9)
                .addComponent(CursoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cursoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoAlunoActionPerformed
        // crud de aluno para crud curso
        GUIcurso guIcurso = new GUIcurso();
        guIcurso.setVisible(true);
        fecha();
    }//GEN-LAST:event_cursoAlunoActionPerformed

    private void turmaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaAlunoActionPerformed
        //crud de aluno para crud turma
        GUIturma guIturma = new GUIturma();
        guIturma.setVisible(true);
        fecha();
    }//GEN-LAST:event_turmaAlunoActionPerformed

    private void discAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discAlunoActionPerformed
        //crud aluno para crud disciplina
        GUIdisc guIdisc = new GUIdisc();
        guIdisc.setVisible(true);
        fecha();
    }//GEN-LAST:event_discAlunoActionPerformed

    private void pesqAlunoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqAlunoBTActionPerformed
        String pk2 = RATF.getText();
        DAOaluno daOaluno = new DAOaluno();
        

        Aluno aluno = new Aluno();
        aluno = daOaluno.consultar(Integer.valueOf(pk2));

        if (null == aluno) {
            tabelaAluno.setVisible(false);
            JOptionPane.showMessageDialog(null, "Esse aluno não existe, adicicone ele!");
            nomeAlunoTF.setText("");
            CursoSelect.setText("");
            emailAlunoTF.setText("");
            telefoneTF.setText("");
           

        } else {
            tabelaAluno.setVisible(false);
            nomeAlunoTF.setText(aluno.getNome());
            emailAlunoTF.setText(aluno.getEmail());
            telefoneTF.setText(aluno.getTelefone());
            String pk = aluno.getCursoNomeCurso().getNomeCurso();
            CursoSelect.setText(pk);
            
            
        }

        nomeAlunoTF.setEditable(false);
        emailAlunoTF.setEditable(false);
        telefoneTF.setEditable(false);
        comboCurso.setEnabled(false);
        CursoSelect.setEditable(false);
       
    }//GEN-LAST:event_pesqAlunoBTActionPerformed

    private void addAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlunoActionPerformed
        // função add
        nomeAlunoTF.setEditable(true);
        emailAlunoTF.setEditable(true);
        telefoneTF.setEditable(true);
        comboCurso.setEnabled(true);
        CursoSelect.setEditable(false);
        RATF.setEditable(false);
        tabelaAluno.setVisible(false);

    }//GEN-LAST:event_addAlunoActionPerformed

    private void saveAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAlunoActionPerformed
        // função salvar

        String pk2 = RATF.getText();
        DAOcurso daOcurso = new DAOcurso();
        DAOaluno daOaluno = new DAOaluno();
        DefaultTableModel model;
        model = (DefaultTableModel) tabelaAluno.getModel();
        int ra = Integer.valueOf(pk2);

        Aluno aluno = new Aluno();

        String nome = nomeAlunoTF.getText();
        String email = emailAlunoTF.getText();
        String tel = telefoneTF.getText();
        aluno = daOaluno.consultar(ra);
        String pk = String.valueOf(comboCurso.getSelectedItem());
        Curso curso = new Curso();
       

        if (null == curso) {
            JOptionPane.showMessageDialog(null, "Esse curso não existe, adicicone ele primeiro!");
            nomeAlunoTF.setEditable(false);
            emailAlunoTF.setEditable(false);
            telefoneTF.setEditable(false);
            comboCurso.setEditable(false);
            CursoSelect.setEditable(false);
            nomeAlunoTF.setText("");
            emailAlunoTF.setText("");
            telefoneTF.setText("");
            
            RATF.setEditable(true);

        } else {
            if (null == aluno) {
                Aluno aluno2 = new Aluno();
                aluno2.setNome(nome);
                aluno2.setEmail(email);
                aluno2.setCursoNomeCurso(daOcurso.consultar(pk));
                CursoSelect.setText(pk);
                aluno2.setTelefone(tel);
                aluno2.setRa(ra);

                daOaluno.criar(aluno2);

            } else {
                aluno.setNome(nome);
                aluno.setEmail(email);
                aluno.setCursoNomeCurso(daOcurso.consultar(pk));
                aluno.setTelefone(tel);
                CursoSelect.setText(pk);
                daOaluno.atualizar(aluno);

            }

            nomeAlunoTF.setEditable(false);
            emailAlunoTF.setEditable(false);
            telefoneTF.setEditable(false);
            comboCurso.setEnabled(false);
            CursoSelect.setEditable(false);
            RATF.setEditable(true);

        }
        tabelaAluno.setVisible(false);

    }//GEN-LAST:event_saveAlunoActionPerformed

    private void attAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attAlunoActionPerformed
        nomeAlunoTF.setEditable(true);
            emailAlunoTF.setEditable(true);
            telefoneTF.setEditable(true);
            comboCurso.setEnabled(true);
            RATF.setEditable(false);
            tabelaAluno.setVisible(false);
            CursoSelect.setEditable(false);
    }//GEN-LAST:event_attAlunoActionPerformed

    private void delAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAlunoActionPerformed
        String pk2 = RATF.getText();
        DAOaluno daOaluno = new DAOaluno();
        
        daOaluno.deletar(Integer.valueOf(pk2));
        tabelaAluno.setVisible(false);
        nomeAlunoTF.setText("");
            emailAlunoTF.setText("");
            telefoneTF.setText("");
            CursoSelect.setText("");
            comboCurso.setEnabled(false);
            RATF.setText("");
        
    }//GEN-LAST:event_delAlunoActionPerformed

    private void listAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAlunoActionPerformed
        DAOaluno daOaluno = new DAOaluno();
        DefaultTableModel model;
        model = (DefaultTableModel) tabelaAluno.getModel();
      

        List<Aluno> lista2 = daOaluno.findall();
        try{
        for(int n=0;n<1000;n++){
            
            model.removeRow(n);
        }
        }catch(Exception e){
            
        }
        lista2.forEach(aluno -> {
            model.insertRow(model.getRowCount(), new Object[]{aluno.getRa(),aluno.getNome(),aluno.getEmail(),aluno.getTelefone(),aluno.getCursoNomeCurso().getNomeCurso()});
        });
        tabelaAluno.setVisible(true);
        
    }//GEN-LAST:event_listAlunoActionPerformed

    private void comboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCursoActionPerformed

        
    }//GEN-LAST:event_comboCursoActionPerformed

    private void buscarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBTActionPerformed
        DAOcurso daOcurso = new DAOcurso();
        List<Curso> listaCurso = daOcurso.list();
        for (Curso curso : listaCurso) {
             comboCurso.addItem(curso.getNomeCurso());
        }
     
        
    }//GEN-LAST:event_buscarBTActionPerformed

    private void RATFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RATFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RATFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIaluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIaluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIaluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIaluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIaluno().setVisible(true);
            }
        });
    }
     public void fecha(){
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CursoSelect;
    private javax.swing.JTextField RATF;
    private javax.swing.JMenuItem addAluno;
    private javax.swing.JMenuItem attAluno;
    private javax.swing.JButton buscarBT;
    private javax.swing.JComboBox<String> comboCurso;
    private javax.swing.JMenuItem cursoAluno;
    private javax.swing.JMenuItem delAluno;
    private javax.swing.JMenuItem discAluno;
    private javax.swing.JTextField emailAlunoTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem listAluno;
    private javax.swing.JTextField nomeAlunoTF;
    private javax.swing.JButton pesqAlunoBT;
    private javax.swing.JMenuItem saveAluno;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JTextField telefoneTF;
    private javax.swing.JMenuItem turmaAluno;
    // End of variables declaration//GEN-END:variables
}
