/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import DAOs.DAOcurso;
import Entidades.Curso;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class GUIcurso extends javax.swing.JFrame {

    /**
     * Creates new form GUIcurso
     */
    public GUIcurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCurso = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nomeCursoTF = new javax.swing.JTextField();
        pesqCursoBT = new javax.swing.JButton();
        duracaoTF = new javax.swing.JTextField();
        coordTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdd = new javax.swing.JMenu();
        addCurso = new javax.swing.JMenuItem();
        attCurso = new javax.swing.JMenuItem();
        delCurso = new javax.swing.JMenuItem();
        saveCurso = new javax.swing.JMenuItem();
        listCurso = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        alunoCurso = new javax.swing.JMenuItem();
        turmaCurso = new javax.swing.JMenuItem();
        discCurso = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));

        tabelaCurso.setBackground(new java.awt.Color(255, 0, 255));
        tabelaCurso.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        tabelaCurso.setForeground(new java.awt.Color(255, 255, 255));
        tabelaCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Curso", "Duração", "Coordenador"
            }
        ));
        jScrollPane1.setViewportView(tabelaCurso);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel1.setText("Nome do curso:");

        pesqCursoBT.setBackground(new java.awt.Color(153, 255, 153));
        pesqCursoBT.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        pesqCursoBT.setForeground(new java.awt.Color(0, 0, 51));
        pesqCursoBT.setText("Pesquisar");
        pesqCursoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqCursoBTActionPerformed(evt);
            }
        });

        duracaoTF.setForeground(new java.awt.Color(153, 153, 153));

        coordTF.setForeground(new java.awt.Color(153, 153, 153));
        coordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordTFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel2.setText("Duração em semestres:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setText("Coordenador:");

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 255));

        menuAdd.setText("Arquivo");

        addCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/botao-adicionar.png"))); // NOI18N
        addCurso.setText("Adicionar");
        addCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCursoActionPerformed(evt);
            }
        });
        menuAdd.add(addCurso);

        attCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar.png"))); // NOI18N
        attCurso.setText("Atualizar");
        attCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attCursoActionPerformed(evt);
            }
        });
        menuAdd.add(attCurso);

        delCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lixeira.png"))); // NOI18N
        delCurso.setText("Deletar");
        delCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCursoActionPerformed(evt);
            }
        });
        menuAdd.add(delCurso);

        saveCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/verificado.png"))); // NOI18N
        saveCurso.setText("Salvar");
        saveCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCursoActionPerformed(evt);
            }
        });
        menuAdd.add(saveCurso);

        listCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lista-de-papel.png"))); // NOI18N
        listCurso.setText("Listar");
        listCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCursoActionPerformed(evt);
            }
        });
        menuAdd.add(listCurso);

        jMenuBar1.add(menuAdd);

        jMenu2.setText("Cruds");

        alunoCurso.setText("Crud Aluno");
        alunoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoCursoActionPerformed(evt);
            }
        });
        jMenu2.add(alunoCurso);

        turmaCurso.setText("Crud Turma");
        turmaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaCursoActionPerformed(evt);
            }
        });
        jMenu2.add(turmaCurso);

        discCurso.setText("Crud disciplina");
        discCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discCursoActionPerformed(evt);
            }
        });
        jMenu2.add(discCurso);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(duracaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(nomeCursoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesqCursoBT))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(coordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeCursoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesqCursoBT))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCursoActionPerformed
        //função adicionar
        nomeCursoTF.setEditable(false);

        duracaoTF.setEditable(true);

        coordTF.setEditable(true);


    }//GEN-LAST:event_addCursoActionPerformed

    private void coordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coordTFActionPerformed

    private void alunoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoCursoActionPerformed
        //caminho para chegar ao crud aluno do crud curso
        GUIaluno guIaluno = new GUIaluno();
        guIaluno.setVisible(true);
        fecha();

    }//GEN-LAST:event_alunoCursoActionPerformed

    private void turmaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaCursoActionPerformed
        //caminho do crud curso para o crud turma
        GUIturma guIturma = new GUIturma();
        guIturma.setVisible(true);
        fecha();
    }//GEN-LAST:event_turmaCursoActionPerformed

    private void discCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discCursoActionPerformed
        // caminho do crud curso para o crud disciplina
        GUIdisc guIdisc = new GUIdisc();
        guIdisc.setVisible(true);
        fecha();
    }//GEN-LAST:event_discCursoActionPerformed

    private void pesqCursoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqCursoBTActionPerformed

        String pk = nomeCursoTF.getText();
        DAOcurso daOcurso = new DAOcurso();

        Curso curso = new Curso();
        curso = daOcurso.consultar(pk);

        if (null == curso) {
            tabelaCurso.setVisible(false);
            JOptionPane.showMessageDialog(null, "Esse curso não existe, adicicone ele!");
            duracaoTF.setText("");

            coordTF.setText("");

        } else {
            tabelaCurso.setVisible(false);
            duracaoTF.setText(String.valueOf(curso.getDuracao()));
            coordTF.setText(curso.getCoordenador());
        }

        duracaoTF.setEditable(false);

        coordTF.setEditable(false);


    }//GEN-LAST:event_pesqCursoBTActionPerformed

    private void saveCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCursoActionPerformed
        //função salvar
        String pk = nomeCursoTF.getText();
        DAOcurso daOcurso = new DAOcurso();
        DefaultTableModel model;
        model = (DefaultTableModel) tabelaCurso.getModel();

        Curso curso = new Curso();

        String duracao = duracaoTF.getText();
        String coord = coordTF.getText();
        curso = daOcurso.consultar(pk);

        if (null == curso) {
            Curso curso2 = new Curso();
            curso2.setDuracao(Integer.valueOf(duracao));
            curso2.setCoordenador(coord);
            curso2.setNomeCurso(pk);

            daOcurso.criar(curso2);

        } else {
            curso.setDuracao(Integer.valueOf(duracao));
            curso.setCoordenador(coord);

            daOcurso.atualizar(curso);

        }

        nomeCursoTF.setEditable(true);
        duracaoTF.setEditable(false);

        coordTF.setEditable(false);
        tabelaCurso.setVisible(false);


    }//GEN-LAST:event_saveCursoActionPerformed

    private void attCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attCursoActionPerformed
        // função alterar
        nomeCursoTF.setEditable(false);
        duracaoTF.setEditable(true);

        coordTF.setEditable(true);
        tabelaCurso.setVisible(false);


    }//GEN-LAST:event_attCursoActionPerformed

    private void delCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCursoActionPerformed
        //função deletar
        String pk = nomeCursoTF.getText();
        DAOcurso daOcurso = new DAOcurso();
        daOcurso.deletar(pk);
        tabelaCurso.setVisible(false);
        nomeCursoTF.setText("");
        duracaoTF.setText("");

        coordTF.setText("");
    }//GEN-LAST:event_delCursoActionPerformed

    private void listCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCursoActionPerformed
        //função listar
        DAOcurso daOcurso = new DAOcurso();
        DefaultTableModel model;
        model = (DefaultTableModel) tabelaCurso.getModel();

        List<Curso> lista2 = daOcurso.findall();
        try{
        for(int n=0;n<1000;n++){
            
            model.removeRow(n);
        }
        }catch(Exception e){
            
        }
        lista2.forEach(curso -> {
            model.insertRow(model.getRowCount(), new Object[]{curso.getNomeCurso(), curso.getDuracao(), curso.getCoordenador()});
        });
        tabelaCurso.setVisible(true);


    }//GEN-LAST:event_listCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIcurso().setVisible(true);
            }
        });
    }
     public void fecha(){
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCurso;
    private javax.swing.JMenuItem alunoCurso;
    private javax.swing.JMenuItem attCurso;
    private javax.swing.JTextField coordTF;
    private javax.swing.JMenuItem delCurso;
    private javax.swing.JMenuItem discCurso;
    private javax.swing.JTextField duracaoTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem listCurso;
    private javax.swing.JMenu menuAdd;
    private javax.swing.JTextField nomeCursoTF;
    private javax.swing.JButton pesqCursoBT;
    private javax.swing.JMenuItem saveCurso;
    private javax.swing.JTable tabelaCurso;
    private javax.swing.JMenuItem turmaCurso;
    // End of variables declaration//GEN-END:variables
}
