/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import java.awt.event.ActionEvent;

/**
 *
 * @author Usuario
 */
public class GUIescolha extends javax.swing.JFrame {

    /**
     * Creates new form GUIescolha
     */
    public GUIescolha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cursoBT = new javax.swing.JButton();
        alunoBT = new javax.swing.JButton();
        turmaBT = new javax.swing.JButton();
        disciplinaBT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escolha seu crud");
        setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("Parabéns!!! Você não é um robo... ");

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel2.setText("Agora escolha em qual crud quer entrar");

        cursoBT.setBackground(new java.awt.Color(0, 0, 204));
        cursoBT.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        cursoBT.setForeground(new java.awt.Color(255, 255, 255));
        cursoBT.setText("Curso");
        cursoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoBTActionPerformed(evt);
            }
        });

        alunoBT.setBackground(new java.awt.Color(0, 0, 204));
        alunoBT.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        alunoBT.setForeground(new java.awt.Color(255, 255, 255));
        alunoBT.setText("Aluno");
        alunoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoBTActionPerformed(evt);
            }
        });

        turmaBT.setBackground(new java.awt.Color(0, 0, 204));
        turmaBT.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        turmaBT.setForeground(new java.awt.Color(255, 255, 255));
        turmaBT.setText("Turma");
        turmaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaBTActionPerformed(evt);
            }
        });

        disciplinaBT.setBackground(new java.awt.Color(0, 0, 204));
        disciplinaBT.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        disciplinaBT.setForeground(new java.awt.Color(255, 255, 255));
        disciplinaBT.setText("Disciplina");
        disciplinaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinaBTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        jLabel3.setText("Apenas lembrando que todos os cruds dependem de um curso cadastrado...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cursoBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(turmaBT, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alunoBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(disciplinaBT, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cursoBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alunoBT, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(turmaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(disciplinaBT, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void turmaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaBTActionPerformed
        turmaBT.addActionListener((ActionEvent ae) -> {
            GUIturma guIturma = new GUIturma();
            guIturma.setVisible(true);
            fchxa();
        });
    }//GEN-LAST:event_turmaBTActionPerformed

    private void cursoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoBTActionPerformed
        cursoBT.addActionListener((ActionEvent ae) -> {
            GUIcurso guIcurso = new GUIcurso();
            guIcurso.setVisible(true);
            fchxa();
        });
    }//GEN-LAST:event_cursoBTActionPerformed

    private void alunoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoBTActionPerformed
        alunoBT.addActionListener((ActionEvent ae) -> {
            GUIaluno guIaluno = new GUIaluno();
            guIaluno.setVisible(true);
            fchxa();
            
        });
    }//GEN-LAST:event_alunoBTActionPerformed

    private void disciplinaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaBTActionPerformed
        disciplinaBT.addActionListener((ActionEvent ae) -> {
            GUIdisc guIdisc = new GUIdisc();
            guIdisc.setVisible(true);
            fchxa();
        });
    }//GEN-LAST:event_disciplinaBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIescolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIescolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIescolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIescolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIescolha().setVisible(true);
            }
        });
    }
     public void fchxa(){
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alunoBT;
    private javax.swing.JButton cursoBT;
    private javax.swing.JButton disciplinaBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton turmaBT;
    // End of variables declaration//GEN-END:variables
}
