/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import DAOs.DAOcurso;
import DAOs.DAOturma;
import Entidades.Curso;
import Entidades.Turma;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class GUIturma extends javax.swing.JFrame {

    /**
     * Creates new form GUIturma
     */
    public GUIturma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codTurmaTF = new javax.swing.JTextField();
        pesqTurmaBT = new javax.swing.JButton();
        periodoTF = new javax.swing.JTextField();
        CursoSelect = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTurma = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboCurso = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addTurma = new javax.swing.JMenuItem();
        saveTurma = new javax.swing.JMenuItem();
        attTurma = new javax.swing.JMenuItem();
        delTurma = new javax.swing.JMenuItem();
        listTurma = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cursoTurma = new javax.swing.JMenuItem();
        alunoTurma = new javax.swing.JMenuItem();
        discTurma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crud Turma");

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel1.setText("Código da turma:");

        pesqTurmaBT.setBackground(new java.awt.Color(153, 255, 153));
        pesqTurmaBT.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        pesqTurmaBT.setForeground(new java.awt.Color(0, 0, 51));
        pesqTurmaBT.setText("Pesquisar");
        pesqTurmaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqTurmaBTActionPerformed(evt);
            }
        });

        periodoTF.setForeground(new java.awt.Color(153, 153, 153));
        periodoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoTFActionPerformed(evt);
            }
        });

        CursoSelect.setForeground(new java.awt.Color(153, 153, 153));
        CursoSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursoSelectActionPerformed(evt);
            }
        });

        tabelaTurma.setBackground(new java.awt.Color(255, 0, 102));
        tabelaTurma.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        tabelaTurma.setForeground(new java.awt.Color(255, 255, 255));
        tabelaTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Periodo", "Curso"
            }
        ));
        jScrollPane1.setViewportView(tabelaTurma);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Periodo:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Curso Selecionado:");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Cursos");

        comboCurso.setBackground(new java.awt.Color(153, 0, 153));
        comboCurso.setForeground(new java.awt.Color(255, 255, 255));
        comboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCursoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Carregar Cursos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 255));

        jMenu1.setText("Arquivo");

        addTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/botao-adicionar.png"))); // NOI18N
        addTurma.setText("Adicionar");
        addTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(addTurma);

        saveTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/verificado.png"))); // NOI18N
        saveTurma.setText("Salvar");
        saveTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(saveTurma);

        attTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar.png"))); // NOI18N
        attTurma.setText("Atualizar");
        attTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(attTurma);

        delTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lixeira.png"))); // NOI18N
        delTurma.setText("Deletar");
        delTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(delTurma);

        listTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lista-de-papel.png"))); // NOI18N
        listTurma.setText("Listar");
        listTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(listTurma);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cruds");

        cursoTurma.setText("Crud Curso");
        cursoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoTurmaActionPerformed(evt);
            }
        });
        jMenu2.add(cursoTurma);

        alunoTurma.setText("Crud Aluno");
        alunoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoTurmaActionPerformed(evt);
            }
        });
        jMenu2.add(alunoTurma);

        discTurma.setText("Crud Disciplina");
        discTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discTurmaActionPerformed(evt);
            }
        });
        jMenu2.add(discTurma);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(codTurmaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(pesqTurmaBT)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CursoSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(periodoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(comboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codTurmaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesqTurmaBT))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CursoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void periodoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoTFActionPerformed
       
    }//GEN-LAST:event_periodoTFActionPerformed

    private void CursoSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursoSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CursoSelectActionPerformed

    private void attTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attTurmaActionPerformed
        codTurmaTF.setEditable(false);
        periodoTF.setEditable(true);
        comboCurso.setEnabled(true);
        CursoSelect.setEditable(true);
        tabelaTurma.setVisible(false);
    }//GEN-LAST:event_attTurmaActionPerformed

    private void alunoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoTurmaActionPerformed
        //curd turma para aluno
        GUIaluno guIaluno = new GUIaluno();
        guIaluno.setVisible(true);
        fecha();
    }//GEN-LAST:event_alunoTurmaActionPerformed

    private void cursoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoTurmaActionPerformed
        //crud turma para curso
        GUIcurso guIcurso = new GUIcurso();
        guIcurso.setVisible(true);
        fecha();
        
    }//GEN-LAST:event_cursoTurmaActionPerformed

    private void discTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discTurmaActionPerformed
        // crud turma para disciplina
        GUIdisc guIdisc = new GUIdisc();
        guIdisc.setVisible(true);
        fecha();
    }//GEN-LAST:event_discTurmaActionPerformed

    private void addTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTurmaActionPerformed
        // função add
        codTurmaTF.setEditable(false);
        comboCurso.setEnabled(true);
        periodoTF.setEditable(true);

        CursoSelect.setEditable(true);
    }//GEN-LAST:event_addTurmaActionPerformed

    private void saveTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTurmaActionPerformed
        String pk2 = codTurmaTF.getText();
        DAOcurso daOcurso = new DAOcurso();
        DAOturma daOturma = new DAOturma();
        DefaultTableModel model;
        model = (DefaultTableModel) tabelaTurma.getModel();

        Turma turma = new Turma();

        String periodo = periodoTF.getText();
        
        turma = daOturma.consultar(pk2);
        String pk = String.valueOf(comboCurso.getSelectedItem());
        Curso curso = new Curso();
        curso = daOcurso.consultar(pk);

        if (null == curso) {
            JOptionPane.showMessageDialog(null, "Esse curso não existe, adicicone ele primeiro!");
            periodoTF.setEditable(false);
            CursoSelect.setEditable(false);
            comboCurso.setEditable(false);
            periodoTF.setText("");
            CursoSelect.setText("");
            codTurmaTF.setEditable(true);

        } else {
            if (null == turma) {
                Turma aluno2 = new Turma();
                aluno2.setPeriodo(Integer.valueOf(periodo));
                aluno2.setCursoNomeCurso(curso);
                aluno2.setCodigo(pk2);
                CursoSelect.setText(pk);
                daOturma.criar(aluno2);

            } else {
                turma.setPeriodo(Integer.valueOf(periodo));
                turma.setCursoNomeCurso(curso);
                CursoSelect.setText(pk);
                daOturma.atualizar(turma);

            }

            periodoTF.setEditable(false);
            CursoSelect.setEditable(false);
            codTurmaTF.setEditable(true);
            comboCurso.setEnabled(false);

        }
        tabelaTurma.setVisible(false);
    }//GEN-LAST:event_saveTurmaActionPerformed

    private void delTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delTurmaActionPerformed
        String pk3 = codTurmaTF.getText();
        DAOturma daOturma = new DAOturma();
        daOturma.deletar(pk3);
        tabelaTurma.setVisible(false);
        codTurmaTF.setText("");
        periodoTF.setText("");
        comboCurso.setEnabled(false);
        CursoSelect.setText("");
    }//GEN-LAST:event_delTurmaActionPerformed

    private void listTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTurmaActionPerformed
        DAOturma daOturma = new DAOturma();
        DefaultTableModel model;
        model = (DefaultTableModel) tabelaTurma.getModel();

        List<Turma> lista2 = daOturma.findall();
        try{
        for(int n=0;n<1000;n++){
            
            model.removeRow(n);
        }
        }catch(Exception e){
            
        }
        lista2.forEach(turma -> {
            model.insertRow(model.getRowCount(), new Object[]{turma.getCodigo(),turma.getPeriodo(),turma.getCursoNomeCurso().getNomeCurso()});
        });
        tabelaTurma.setVisible(true);
    }//GEN-LAST:event_listTurmaActionPerformed

    private void pesqTurmaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqTurmaBTActionPerformed
        String pk3 = codTurmaTF.getText();
        DAOturma daOturma = new DAOturma();

        Turma turma = new Turma();
        turma = daOturma.consultar(pk3);

        if (null == turma) {
            tabelaTurma.setVisible(false);
            JOptionPane.showMessageDialog(null, "Essa turma não existe, adicicone ela!");
            periodoTF.setText("");

            CursoSelect.setText("");

        } else {
            tabelaTurma.setVisible(false);
            periodoTF.setText(String.valueOf(turma.getPeriodo()));
            String pk = turma.getCursoNomeCurso().getNomeCurso();
            CursoSelect.setText(pk);
        }

        periodoTF.setEditable(false);
        comboCurso.setEnabled(false);
        CursoSelect.setEditable(false);
    }//GEN-LAST:event_pesqTurmaBTActionPerformed

    private void comboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCursoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DAOcurso daOcurso = new DAOcurso();
        List<Curso> listaCurso = daOcurso.list();
        for (Curso curso : listaCurso) {
             comboCurso.addItem(curso.getNomeCurso());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIturma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIturma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIturma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIturma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIturma().setVisible(true);
            }
        });
    }
     public void fecha(){
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CursoSelect;
    private javax.swing.JMenuItem addTurma;
    private javax.swing.JMenuItem alunoTurma;
    private javax.swing.JMenuItem attTurma;
    private javax.swing.JTextField codTurmaTF;
    private javax.swing.JComboBox<String> comboCurso;
    private javax.swing.JMenuItem cursoTurma;
    private javax.swing.JMenuItem delTurma;
    private javax.swing.JMenuItem discTurma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem listTurma;
    private javax.swing.JTextField periodoTF;
    private javax.swing.JButton pesqTurmaBT;
    private javax.swing.JMenuItem saveTurma;
    private javax.swing.JTable tabelaTurma;
    // End of variables declaration//GEN-END:variables
}
